### ISSUE TITLE
Crash when clicking logseat sometimes

### ISSUE THREAD

**Issue by Rikmuld** [Rikmuld/CampingMod-mcmod#10]
java.lang.NoClassDefFoundError: org/lwjgl/input/Keyboard
at com.rikmuld.camping.common.objs.entity.EntityMountableBlock.func_70071_h_(EntityMountableBlock.scala:36)
at net.minecraft.world.World.func_72866_a(World.java:2643)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
at net.minecraft.world.World.func_72870_g(World.java:2596)
at net.minecraft.world.World.func_72939_s(World.java:2408)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.input.Keyboard
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:104)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 11 more

**Comment by Rikmuld** [comment]
fixed
