### ISSUE TITLE
Tent placing next to each other error

### ISSUE THREAD

**Issue by Rikmuld** [Rikmuld/CampingMod-mcmod#11]
Report:

Description: Ticking memory connection

java.lang.ClassCastException: com.rikmuld.camping.common.objs.tile.TileEntityTent cannot be cast to com.rikmuld.camping.common.objs.tile.TileEntityWithBounds
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:34)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:36)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at net.minecraft.world.World.func_147449_b(World.java:600)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply$mcZI$sp(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$destroyStructure$1.apply(BoundsStructure.scala:64)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.destroyStructure(BoundsStructure.scala:64)
at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:55)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
at net.minecraft.world.World.func_147465_d(World.java:451)
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$createStructure$1.apply$mcVI$sp(BoundsStructure.scala:58)
at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
at com.rikmuld.camping.misc.BoundsStructure.createStructure(BoundsStructure.scala:57)
at com.rikmuld.camping.common.objs.tile.TileEntityTent.setRotation(TileTent.scala:231)
at com.rikmuld.camping.common.objs.block.BlockWithRotation$class.onBlockPlacedBy(BlockMain.scala:84)
at com.rikmuld.camping.common.objs.block.Tent.func_149689_a(Tent.scala:120)
at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Rikmuld** [comment]
fixed tent error
