### ISSUE TITLE
Shader mod compatibility issue (probably)

### ISSUE THREAD

**Issue by rikmuld** [Rikmuld/CampingMod-mcmod#124]
From a curse forge comment:

<details>
  <summary>Minecraft Crash Report</summary>

WARNING: coremods are present:
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
LoadingPlugin (Quark-r1.4-123.jar)
Plugin (NotEnoughIDs-1.5.4.2.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
ModInject (MineAddons-v2.6-mc1.12.2.jar)
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
FMLPlugin (elulib-0.1.11.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
ForgelinPlugin (Forgelin-1.6.0.jar)
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9-1.12.2-anarchy.jar)
LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
FarseekCoreMod (Farseek-1.12-2.2.5.jar)
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
SSLoadingPlugin (SereneSeasons-1.12.2-1.0.0-universal.jar)
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 4/28/18 11:00 PM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[south, west, north, east]} as it does not exist in BlockStateContainer{block=null, properties=[]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
at com.rikmuld.corerm.objs.States$$anonfun$get$1.apply(States.scala:62)
at com.rikmuld.corerm.objs.States$$anonfun$get$1.apply(States.scala:62)
at scala.Option.map(Option.scala:145)
at com.rikmuld.corerm.objs.States.get(States.scala:62)
at com.rikmuld.corerm.objs.blocks.BlockSimple$class.getState(BlockSimple.scala:50)
at com.rikmuld.corerm.objs.blocks.BlockRM.getState(BlockRM.scala:8)
at com.rikmuld.corerm.objs.blocks.BlockSimple$class.getDirection(BlockSimple.scala:74)
at com.rikmuld.corerm.objs.blocks.BlockRM.getDirection(BlockRM.scala:8)
at com.rikmuld.corerm.objs.blocks.BlockSimple$class.getFacing(BlockSimple.scala:62)
at com.rikmuld.corerm.objs.blocks.BlockRM.getFacing(BlockRM.scala:8)
at com.rikmuld.camping.features.blocks.tent.TileEntityTent$$anonfun$getFacing$1.apply(TileEntityTent.scala:205)
at com.rikmuld.camping.features.blocks.tent.TileEntityTent$$anonfun$getFacing$1.apply(TileEntityTent.scala:204)
at scala.Option.getOrElse(Option.scala:120)
at com.rikmuld.camping.features.blocks.tent.TileEntityTent.getFacing(TileEntityTent.scala:204)
at com.rikmuld.camping.features.blocks.tent.RendererTent.render(RendererTent.scala:47)
at com.rikmuld.camping.features.blocks.tent.RendererTent.func_192841_a(RendererTent.scala:38)
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1011)
at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:374)
at shadersmod.client.Shaders.beginRender(Shaders.java:4390)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1593)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
at com.rikmuld.corerm.objs.States$$anonfun$get$1.apply(States.scala:62)
at com.rikmuld.corerm.objs.States$$anonfun$get$1.apply(States.scala:62)
at scala.Option.map(Option.scala:145)
at com.rikmuld.corerm.objs.States.get(States.scala:62)
at com.rikmuld.corerm.objs.blocks.BlockSimple$class.getState(BlockSimple.scala:50)
at com.rikmuld.corerm.objs.blocks.BlockRM.getState(BlockRM.scala:8)
at com.rikmuld.corerm.objs.blocks.BlockSimple$class.getDirection(BlockSimple.scala:74)
at com.rikmuld.corerm.objs.blocks.BlockRM.getDirection(BlockRM.scala:8)
at com.rikmuld.corerm.objs.blocks.BlockSimple$class.getFacing(BlockSimple.scala:62)
at com.rikmuld.corerm.objs.blocks.BlockRM.getFacing(BlockRM.scala:8)
at com.rikmuld.camping.features.blocks.tent.TileEntityTent$$anonfun$getFacing$1.apply(TileEntityTent.scala:205)
at com.rikmuld.camping.features.blocks.tent.TileEntityTent$$anonfun$getFacing$1.apply(TileEntityTent.scala:204)
at scala.Option.getOrElse(Option.scala:120)
at com.rikmuld.camping.features.blocks.tent.TileEntityTent.getFacing(TileEntityTent.scala:204)
at com.rikmuld.camping.features.blocks.tent.RendererTent.render(RendererTent.scala:47)
at com.rikmuld.camping.features.blocks.tent.RendererTent.func_192841_a(RendererTent.scala:38)

-- Block Entity Details --
Details:
Name: minecraft:camping_tiletent // com.rikmuld.camping.features.blocks.tent.TileEntityTent
Block type: ID #0 (tile.null // com.TominoCZ.FBP.block.FBPAnimationDummyBlock)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (140,64,740), Chunk: (at 12,4,4 in 8,46; contains blocks 128,0,736 to 143,255,751), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1011)
at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:374)
at shadersmod.client.Shaders.beginRender(Shaders.java:4390)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1593)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['SixtyMillionSqrd'/289, l='MpServer', x=141.39, y=64.00, z=738.31]]
Chunk stats: MultiplayerChunkCache: 562, 562
Level seed: 0
Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
Level generator options:
Level spawn location: World: (319,64,20), Chunk: (at 15,4,4 in 19,1; contains blocks 304,0,16 to 319,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 3455 game time, 3455 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 148 total; [EntityItem['item.tile.sea_urchin_tropical'/512, l='MpServer', x=118.88, y=61.00, z=742.51], EntityItem['item.tile.large_sea_anemone'/513, l='MpServer', x=117.44, y=60.00, z=745.33], EntityItem['item.tile.large_sea_anemone'/514, l='MpServer', x=118.52, y=61.00, z=746.20], EntityXaphan['Xaphan'/770, l='MpServer', x=116.50, y=11.00, z=744.50], EntityItem['item.tile.small_sea_urchin'/515, l='MpServer', x=77.53, y=60.00, z=795.19], EntityItem['item.tile.sapling.sugi'/518, l='MpServer', x=189.30, y=88.13, z=789.88], EntityBat['Bat'/780, l='MpServer', x=137.06, y=43.76, z=815.14], EntityIndianGharial['Indian Gharial'/526, l='MpServer', x=148.50, y=72.00, z=817.50], EntityBat['Bat'/529, l='MpServer', x=192.77, y=16.97, z=765.70], EntityWitch['Witch'/785, l='MpServer', x=165.50, y=39.00, z=680.50], EntityItem['item.tile.sapling.sugi'/530, l='MpServer', x=185.69, y=72.00, z=772.88], EntityZombie['Zombie'/786, l='MpServer', x=191.50, y=20.00, z=711.50], EntityBat['Bat'/531, l='MpServer', x=146.52, y=15.68, z=806.90], EntityBat['Bat'/538, l='MpServer', x=148.09, y=50.47, z=793.75], EntityBat['Bat'/539, l='MpServer', x=191.37, y=17.36, z=761.26], EntityBat['Bat'/540, l='MpServer', x=190.69, y=18.24, z=763.22], EntityZombie['Zombie'/1053, l='MpServer', x=196.50, y=20.00, z=707.50], EntityItem['item.tile.bladderwrack'/542, l='MpServer', x=128.97, y=61.00, z=786.13], EntityItem['item.tile.small_sea_anemone'/543, l='MpServer', x=131.78, y=59.00, z=787.66], EntityItem['item.tile.bladderwrack'/545, l='MpServer', x=168.11, y=61.00, z=757.09], EntityPlayerSP['SixtyMillionSqrd'/289, l='MpServer', x=141.39, y=64.00, z=738.31], EntityItem['item.tile.small_sea_anemone'/546, l='MpServer', x=167.62, y=61.00, z=761.14], EntityItem['item.tile.bladderwrack'/547, l='MpServer', x=166.77, y=61.00, z=754.56], EntityItem['item.tile.bladderwrack'/548, l='MpServer', x=168.53, y=61.00, z=758.33], EntityItem['item.tile.large_sea_anemone'/549, l='MpServer', x=162.81, y=61.00, z=761.86], EntitySkeleton['Skeleton'/1328, l='MpServer', x=92.50, y=14.00, z=693.50], EntityItem['item.tile.stone_formations.stone_formation'/1330, l='MpServer', x=113.13, y=16.00, z=677.31], EntitySkeleton['Skeleton'/1335, l='MpServer', x=141.28, y=43.00, z=808.52], EntitySkeleton['Skeleton'/1337, l='MpServer', x=135.50, y=43.00, z=810.50], EntityCreeper['Creeper'/1084, l='MpServer', x=183.50, y=25.00, z=717.50], EntityItem['item.tile.sapling.sugi'/1086, l='MpServer', x=168.13, y=73.00, z=732.13], EntitySkeletonWarrior['Skeleton Warrior'/834, l='MpServer', x=117.50, y=14.00, z=745.50], EntitySkeleton['Skeleton'/1094, l='MpServer', x=116.50, y=39.00, z=768.50], EntityCreeper['Creeper'/1095, l='MpServer', x=114.50, y=39.00, z=769.50], EntityItem['item.tile.gracilaria'/585, l='MpServer', x=124.84, y=60.00, z=735.16], EntityFestiveCreeper['Festive Creeper'/1354, l='MpServer', x=135.50, y=36.00, z=761.50], EntityBat['Bat'/590, l='MpServer', x=172.69, y=18.32, z=687.06], EntitySpider['Spider'/591, l='MpServer', x=168.40, y=17.00, z=685.60], EntityZombieVillager['Zombie Villager'/592, l='MpServer', x=165.81, y=17.00, z=683.48], EntityCreeper['Creeper'/593, l='MpServer', x=164.50, y=17.00, z=682.50], EntityItem['item.tile.large_sea_urchin'/594, l='MpServer', x=160.52, y=60.00, z=679.59], EntityItem['item.tile.large_sea_anemone'/595, l='MpServer', x=161.11, y=62.00, z=678.75], EntitySkeleton['Skeleton'/1364, l='MpServer', x=206.57, y=45.17, z=689.29], EntityItem['item.tile.small_sea_urchin'/596, l='MpServer', x=171.13, y=61.00, z=679.02], EntityItem['item.tile.sapling.sugi'/597, l='MpServer', x=173.69, y=73.00, z=679.09], EntitySquid['Squid'/598, l='MpServer', x=111.68, y=61.92, z=711.67], EntitySquid['Squid'/599, l='MpServer', x=114.03, y=61.21, z=714.44], EntityItem['item.tile.kelp'/600, l='MpServer', x=100.07, y=52.00, z=728.13], EntityItem['item.tile.sapling.sugi'/1368, l='MpServer', x=139.88, y=77.00, z=758.88], EntityCreeper['Creeper'/602, l='MpServer', x=159.50, y=17.00, z=682.50], EntitySkeleton['Skeleton'/603, l='MpServer', x=159.50, y=17.00, z=685.50], EntitySkeleton['Skeleton'/604, l='MpServer', x=158.50, y=17.00, z=686.50], EntityCreeper['Creeper'/1372, l='MpServer', x=73.50, y=32.00, z=699.50], EntityCreeper['Creeper'/1373, l='MpServer', x=72.50, y=32.00, z=699.50], EntityItem['item.tile.large_sea_urchin'/605, l='MpServer', x=157.74, y=61.00, z=677.83], EntityCreeper['Creeper'/1374, l='MpServer', x=75.99, y=33.00, z=700.44], EntityItem['item.tile.kelp'/606, l='MpServer', x=146.94, y=61.00, z=675.34], EntityItem['item.tile.kelp'/607, l='MpServer', x=150.50, y=59.00, z=677.81], EntityItem['item.tile.sea_urchin_tropical'/609, l='MpServer', x=102.24, y=61.00, z=705.49], EntityItem['item.tile.small_sea_urchin'/610, l='MpServer', x=103.13, y=61.00, z=707.99], EntitySquid['Squid'/611, l='MpServer', x=109.66, y=62.46, z=710.34], EntitySquid['Squid'/612, l='MpServer', x=109.80, y=61.52, z=709.70], EntityItem['item.tile.sapling.sugi'/1380, l='MpServer', x=158.79, y=64.00, z=770.91], EntityFestiveCreeper['Festive Creeper'/1135, l='MpServer', x=138.50, y=39.00, z=777.50], EntityItem['item.tile.flower_1.miners_delight'/623, l='MpServer', x=126.81, y=15.00, z=684.79], EntityItem['item.tile.small_sea_urchin'/624, l='MpServer', x=99.77, y=61.00, z=702.88], EntityItem['item.tile.gracilaria'/625, l='MpServer', x=98.40, y=61.00, z=701.64], EntityLatchedRenderer['unknown'/629, l='MpServer', x=172.09, y=90.23, z=781.36], EntityLatchedRenderer['unknown'/630, l='MpServer', x=172.09, y=90.23, z=781.36], EntityZombie['Zombie'/1398, l='MpServer', x=90.50, y=18.00, z=794.50], EntityBat['Bat'/631, l='MpServer', x=131.52, y=45.13, z=818.62], EntitySpider['Spider'/635, l='MpServer', x=118.50, y=40.00, z=767.50], EntityRooster['Rooster'/638, l='MpServer', x=58.64, y=63.00, z=840.51], EntitySkeleton['Skeleton'/1150, l='MpServer', x=171.50, y=19.00, z=668.50], EntityRooster['Rooster'/639, l='MpServer', x=58.50, y=63.36, z=841.76], EntityCreeper['Creeper'/640, l='MpServer', x=147.50, y=14.00, z=812.50], EntitySpider['Spider'/643, l='MpServer', x=156.50, y=16.00, z=680.50], EntityBat['Bat'/1411, l='MpServer', x=176.49, y=17.12, z=689.45], EntityHerma['Herma'/903, l='MpServer', x=84.45, y=33.00, z=696.50], EntityBat['Bat'/1426, l='MpServer', x=183.37, y=18.29, z=697.39], EntityItem['item.tile.sapling.sugi'/1171, l='MpServer', x=203.18, y=79.00, z=717.17], EntityItem['item.tile.sapling.sugi'/1437, l='MpServer', x=203.13, y=71.00, z=720.88], EntityEnchantedBook['Bewitched Tome'/1453, l='MpServer', x=161.50, y=17.00, z=682.50], EntitySkeletonWarrior['Skeleton Warrior'/1454, l='MpServer', x=114.50, y=14.00, z=683.50], EntityItem['item.tile.sapling.sugi'/1206, l='MpServer', x=163.88, y=64.00, z=777.13], EntityLatchedRenderer['unknown'/450, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/453, l='MpServer', x=172.09, y=90.23, z=781.36], EntityItem['item.tile.sapling.sugi'/966, l='MpServer', x=169.88, y=98.13, z=801.90], EntityLatchedRenderer['unknown'/455, l='MpServer', x=172.09, y=90.23, z=781.36], EntitySpider['Spider'/458, l='MpServer', x=195.43, y=19.00, z=711.44], EntityCreeper['Creeper'/459, l='MpServer', x=193.88, y=19.00, z=712.50], EntitySkeleton['Skeleton'/1227, l='MpServer', x=204.50, y=22.00, z=756.50], EntityCreeper['Creeper'/460, l='MpServer', x=193.30, y=19.00, z=712.50], EntityItem['item.tile.mushroom'/461, l='MpServer', x=198.88, y=79.00, z=713.88], EntityItem['item.tile.small_sea_anemone'/462, l='MpServer', x=115.96, y=59.00, z=787.90], EntityItem['item.tile.sea_urchin_tropical'/463, l='MpServer', x=113.06, y=57.00, z=784.19], EntityItem['item.tile.sapling.sugi'/464, l='MpServer', x=117.85, y=67.13, z=792.88], EntityItem['item.tile.elegance_coral'/466, l='MpServer', x=167.11, y=61.00, z=746.94], EntityItem['item.tile.mixed_coral_plates'/467, l='MpServer', x=166.77, y=61.00, z=749.76], EntityItem['item.tile.lettuce_coral'/468, l='MpServer', x=168.07, y=61.00, z=747.53], EntityBat['Bat'/469, l='MpServer', x=143.96, y=40.48, z=755.37], EntityBat['Bat'/470, l='MpServer', x=146.25, y=39.35, z=756.14], EntityCreeper['Creeper'/471, l='MpServer', x=192.24, y=19.00, z=710.58], EntityItem['item.tile.gracilaria'/472, l='MpServer', x=179.88, y=60.00, z=713.59], EntityIndianGharial['Indian Gharial'/473, l='MpServer', x=110.50, y=64.00, z=788.50], EntityItem['item.tile.large_sea_anemone'/475, l='MpServer', x=155.85, y=61.00, z=737.36], EntityItem['item.tile.gracilaria'/476, l='MpServer', x=155.32, y=61.00, z=739.48], EntityZombie['Zombie'/1500, l='MpServer', x=90.50, y=18.00, z=793.50], EntityItem['item.tile.small_sea_urchin'/477, l='MpServer', x=157.47, y=61.00, z=738.98], EntityItem['item.tile.sea_grass'/478, l='MpServer', x=149.23, y=61.00, z=750.56], EntityItem['item.tile.sea_grass'/479, l='MpServer', x=149.33, y=61.00, z=744.45], EntityItem['item.tile.sapling.sugi'/1503, l='MpServer', x=186.39, y=76.00, z=688.13], EntityItem['item.tile.sea_grass'/480, l='MpServer', x=150.40, y=61.00, z=746.94], EntitySkeleton['Skeleton'/736, l='MpServer', x=139.50, y=43.00, z=810.50], EntityItem['item.tile.sea_grass'/481, l='MpServer', x=152.68, y=61.00, z=744.63], EntityZombie['Zombie'/482, l='MpServer', x=116.50, y=37.00, z=771.50], EntityItem['item.tile.sapling.sugi'/738, l='MpServer', x=170.88, y=64.00, z=776.43], EntityItem['item.tile.mushroom'/483, l='MpServer', x=186.15, y=17.00, z=695.84], EntityItem['item.tile.mushroom'/484, l='MpServer', x=181.79, y=16.00, z=691.79], EntityItem['item.item.seed_hemp'/485, l='MpServer', x=180.13, y=16.00, z=695.00], EntitySkeleton['Skeleton'/742, l='MpServer', x=130.79, y=46.00, z=814.50], EntityBat['Bat'/486, l='MpServer', x=179.75, y=17.13, z=691.23], EntityDepthsGhoul['Depths Ghoul'/743, l='MpServer', x=137.50, y=43.00, z=814.50], EntityItem['item.tile.sea_grass'/487, l='MpServer', x=180.42, y=60.00, z=702.12], EntityItem['item.tile.sea_urchin_tropical'/488, l='MpServer', x=174.66, y=61.00, z=718.02], EntityItem['item.tile.gracilaria'/489, l='MpServer', x=165.05, y=60.00, z=717.52], EntityItem['item.tile.gracilaria'/490, l='MpServer', x=163.25, y=61.00, z=717.08], EntityItem['item.tile.lettuce_coral'/491, l='MpServer', x=151.29, y=61.00, z=726.55], EntityItem['item.tile.brain_coral'/492, l='MpServer', x=153.78, y=60.00, z=722.88], EntityItem['item.tile.sea_grass'/493, l='MpServer', x=150.81, y=61.00, z=728.63], EntitySquid['Squid'/494, l='MpServer', x=144.76, y=62.59, z=724.49], EntityAcidSplash['entity.acidsplash.name'/1518, l='MpServer', x=116.49, y=11.25, z=744.36], EntitySkeleton['Skeleton'/752, l='MpServer', x=144.50, y=39.00, z=755.50], EntityItem['item.tile.large_sea_anemone'/499, l='MpServer', x=115.88, y=61.00, z=763.07], EntityItem['item.tile.bladderwrack'/500, l='MpServer', x=114.88, y=61.00, z=764.25], EntityItem['item.tile.sapling.sugi'/756, l='MpServer', x=126.31, y=69.00, z=798.11], EntityItem['item.tile.kelp'/501, l='MpServer', x=98.24, y=59.00, z=782.87], EntityItem['item.tile.sea_grass'/502, l='MpServer', x=94.10, y=62.00, z=789.46], EntityItem['item.tile.gracilaria'/503, l='MpServer', x=80.80, y=61.00, z=794.88], EntityItem['item.tile.sea_urchin_tropical'/504, l='MpServer', x=179.73, y=61.00, z=675.08], EntityItem['item.tile.sea_urchin_tropical'/505, l='MpServer', x=158.88, y=61.00, z=717.46], EntityItem['item.tile.fire_coral'/506, l='MpServer', x=158.96, y=61.00, z=717.71], EntitySquid['Squid'/507, l='MpServer', x=151.29, y=59.34, z=717.04], EntityLatchedRenderer['unknown'/763, l='MpServer', x=141.39, y=64.00, z=738.31], EntityItem['item.tile.sea_grass'/508, l='MpServer', x=142.71, y=61.00, z=733.84], EntityXaphan['Xaphan'/509, l='MpServer', x=115.35, y=18.59, z=744.35], EntityItem['item.tile.small_sea_anemone'/510, l='MpServer', x=122.39, y=60.00, z=736.71], EntityItem['item.tile.elegance_coral'/511, l='MpServer', x=120.88, y=61.00, z=739.02]]
Retry entities: 5 total; [EntityLatchedRenderer['unknown'/450, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/453, l='MpServer', x=172.09, y=90.23, z=781.36], EntityLatchedRenderer['unknown'/629, l='MpServer', x=172.09, y=90.23, z=781.36], EntityLatchedRenderer['unknown'/630, l='MpServer', x=172.09, y=90.23, z=781.36], EntityLatchedRenderer['unknown'/455, l='MpServer', x=172.09, y=90.23, z=781.36]]
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3964540080 bytes (3780 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
FML: MCP 9.42 Powered by Forge 14.23.2.2654 Optifine OptiFine_1.12.2_HD_U_D1 167 mods loaded, 167 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:--------- |:-------------------- |:------------------------ |:--------------------------------------------- |:-------
</details>

**Comment by rikmuld** [comment]
From a curse forge comment:
"Fixed in the latest update. Yay!"

Even though the relevant code didn't change much, may need further investigation.
