### ISSUE TITLE
RikMuldsCore causes game to crash on launch

### ISSUE THREAD

**Issue by LadyGwynn** [Rikmuld/CampingMod-mcmod#133]
I installed The Camping Mod (version 2.4.3) without realizing it needed a core mod. Minecraft launched, but told me I was missing corerm 1.3.1 or above and would not let me continue.

I found, downloaded, and installed the latest release (1.3.3) of RikMuldsCore, but upon trying to launch, the game crashed and said, "It looks like you are using an unsupported modified version of the game."

Thinking it might be an issue with the version, I downgraded to RikMuldsCore 1.3.1, but the issue persisted.

I'm not sure how to fix this issue.

Here is the crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.1.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 9/4/18 12:53 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mia/craftstudio/IPackReaderCallback
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:529)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mia.craftstudio.IPackReaderCallback
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:529)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 216124128 bytes (206 MB) / 536870912 bytes (512 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 Optifine OptiFine_1.12.2_HD_U_E2 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                               | Signature                                |
	|:----- |:-------------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UC    | minecraft            | 1.12.2       | minecraft.jar                        | None                                     |
	| UC    | mcp                  | 9.42         | minecraft.jar                        | None                                     |
	| UC    | FML                  | 8.0.99.99    | forge-1.12.2-14.23.4.2758.jar        | None                                     |
	| UC    | forge                | 14.23.4.2758 | forge-1.12.2-14.23.4.2758.jar        | None                                     |
	| UC    | otgcore              | 1.12.2 - v7  | minecraft.jar                        | None                                     |
	| UC    | babymobs             | 1.5.5        | BabyMobs-1.12-1.5.5.jar              | None                                     |
	| UC    | baubles              | 1.5.2        | Baubles-1.12-1.5.2.jar               | None                                     |
	| UC    | betterunderground    | 1.1.2        | Better-Underground-Mod-1.12.2.jar    | None                                     |
	| UC    | openterraingenerator | v6           | OpenTerrainGenerator-1.12.2+-+v6.jar | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UC    | biomebundle          | 5.1          | Biome_Bundle-1.12.2-v6.1.jar         | None                                     |
	| UC    | birdsnests           | 2.1.0        | BirdsNests1.12.2-2.1.0.jar           | None                                     |
	| U     | props                | 2.6.1        | Decocraft-2.6.1_1.12.2.jar           | None                                     |
	| U     | grapplemod           | 1.12.2-v11.1 | grapplemod-v11.1-1.12.2.jar          | None                                     |
	| U     | gravestone           | 1.10.1       | gravestone-1.10.1.jar                | None                                     |
	| U     | jei                  | 4.11.0.212   | jei_1.12.2-4.11.0.212.jar            | None                                     |
	| U     | journeymap           | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar          | None                                     |
	| U     | lex                  | 1.0.8        | LibEx-1.12.2-1.0.8.jar               | None                                     |
	| U     | lucky                | 7.5.0        | LuckyBlock_1-12_v7-5-0.zip           | None                                     |
	| U     | memeinabottle        | 2.0.0        | MemeInABottle-1.12.X-2.0.0.jar       | None                                     |
	| U     | nex                  | 2.0.8        | NetherEx-1.12.2-2.0.8.jar            | None                                     |
	| U     | owls                 | 1.0          | Owls-Mod-1.12.2.jar                  | None                                     |
	| U     | randomthings         | 4.2.1.2      | RandomThings-MC1.12.2-4.2.1.2.jar    | None                                     |
	| U     | corerm               | 1.3.1        | RikMuldsCore_1.3.1.jar               | None                                     |
	| U     | roguelike            | 1.8.0        | RoguelikeDungeons-1.12.2-1.8.0.jar   | None                                     |
	| U     | camping              | 2.4.3        | TheCampingMod_2.4.3.jar              | None                                     |
	| U     | bspkrscore           | at_0.9       | Treecapitator-1.12-at_0.9a.jar       | None                                     |
	| U     | treecapitator        | at_0.9       | Treecapitator-1.12-at_0.9a.jar       | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.1.2.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13537 Compatibility Profile Context 24.20.13001.1010' Renderer: 'AMD Radeon HD 7800 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2758
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7800 Series GL version 4.5.13537 Compatibility Profile Context 24.20.13001.1010, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Updated Vanilla V2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13537 Compatibility Profile Context 24.20.13001.1010
	OpenGlRenderer: AMD Radeon HD 7800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by LadyGwynn** [comment]
Further investigation revealed that it was a conflict between RikMuldsCore and Decocraft 2.6.0+
Downgrading to Decocraft 2.5.5 fixed the issue.
