### ISSUE TITLE
Sleeping bag render error

### ISSUE THREAD

**Issue by Rikmuld** [Rikmuld/CampingMod-mcmod#15]
Any attempt at placing down a tent crashes with the following log:

scala.MatchError: 345 (of class java.lang.Integer)
        at com.rikmuld.camping.client.render.objs.SleepingBagRender.func_147500_a(SleepingBagRender.scala:23)
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
        at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
        at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Rikmuld** [comment]
fixed error
