### ISSUE TITLE
ticking loop

### ISSUE THREAD

**Issue by ArcLP** [Rikmuld/CampingMod-mcmod#25]
1.7.10
 version 2.1f
using cauldron.  you know what could caue it?

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 14/04/15 07:45
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:59)
	at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:40)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at net.minecraft.world.gen.feature.WorldGenLakes.func_76484_a(SourceFile:79)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:397)
	at org.bukkit.craftbukkit.v1_7_R4.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:57)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by Rikmuld** [comment]
Fixed
