### ISSUE TITLE
The camping inventory armor slots don't accept skulls

### ISSUE THREAD

**Issue by Rikmuld** [Rikmuld/CampingMod-mcmod#44]
I downloaded this mod and now Minecraft will not launch.  Getting this error:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/26/15 11:33 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.item.ItemSkull cannot be cast to net.minecraft.item.ItemArmor
at com.rikmuld.camping.EventsS$$anonfun$onPlayerTick$1.apply$mcZI$sp(Events.scala:192)
at com.rikmuld.camping.EventsS$$anonfun$onPlayerTick$1.apply(Events.scala:192)
at com.rikmuld.camping.EventsS$$anonfun$onPlayerTick$1.apply(Events.scala:192)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
at com.rikmuld.camping.EventsS.onPlayerTick(Events.scala:192)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_EventsS_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:386)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:219)
at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:119)
at net.minecraft.world.World.func_72866_a(World.java:1880)
at net.minecraft.world.World.func_72870_g(World.java:1850)
at net.minecraft.world.World.func_72939_s(World.java:1679)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2094)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at com.rikmuld.camping.EventsS$$anonfun$onPlayerTick$1.apply$mcZI$sp(Events.scala:192)
at com.rikmuld.camping.EventsS$$anonfun$onPlayerTick$1.apply(Events.scala:192)
at com.rikmuld.camping.EventsS$$anonfun$onPlayerTick$1.apply(Events.scala:192)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
at com.rikmuld.camping.EventsS.onPlayerTick(Events.scala:192)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_EventsS_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:386)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:219)
at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:119)
at net.minecraft.world.World.func_72866_a(World.java:1880)
at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
Entity ID: 173
Entity Name: FrenchFryCam
Entity's Exact location: 90.01, 69.00, 1199.05
Entity's Block location: 90.00,69.00,1199.00 - World: (90,69,1199), Chunk: (at 10,4,15 in 5,74; contains blocks 80,0,1184 to 95,255,1199), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
Entity's Momentum: 0.00, 0.00, 0.00
Entity's Rider: ~~ERROR~~ NullPointerException: null
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1679)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP'FrenchFryCam'/173, l='MpServer', x=90.01, y=69.00, z=1199.05]]
Chunk stats: MultiplayerChunkCache: 150, 150
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: 28.00,64.00,1128.00 - World: (28,64,1128), Chunk: (at 12,4,8 in 1,70; contains blocks 16,0,1120 to 31,255,1135), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
Level time: 80489 game time, 104366 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 74 total; [EntityPig'Pig'/137, l='MpServer', x=149.53, y=65.00, z=1210.19], EntityPig['Pig'/136, l='MpServer', x=156.78, y=68.00, z=1211.31], EntityChicken['Chicken'/140, l='MpServer', x=145.34, y=65.00, z=1276.75], EntityBat['Bat'/143, l='MpServer', x=159.41, y=19.00, z=1132.66], EntityBat['Bat'/129, l='MpServer', x=148.97, y=22.16, z=1121.53], EntityPig['Pig'/135, l='MpServer', x=147.63, y=64.00, z=1211.84], EntitySquid['Squid'/134, l='MpServer', x=139.81, y=57.78, z=1156.22], EntityChicken['Chicken'/147, l='MpServer', x=162.25, y=62.44, z=1237.09], EntityChicken['Chicken'/150, l='MpServer', x=166.53, y=68.00, z=1268.94], EntityPig['Pig'/42, l='MpServer', x=22.13, y=70.00, z=1230.78], EntityPig['Pig'/43, l='MpServer', x=29.94, y=71.00, z=1246.59], EntityBat['Bat'/41, l='MpServer', x=28.19, y=29.31, z=1124.81], EntityPig['Pig'/44, l='MpServer', x=29.69, y=69.00, z=1227.66], EntityPig['Pig'/51, l='MpServer', x=43.50, y=66.00, z=1265.69], EntityBat['Bat'/50, l='MpServer', x=36.06, y=37.00, z=1263.59], EntityVillager['Villager'/49, l='MpServer', x=40.66, y=64.00, z=1182.84], EntityVillager['Villager'/59, l='MpServer', x=47.66, y=65.00, z=1189.09], EntityVillager['Villager'/58, l='MpServer', x=67.47, y=66.00, z=1178.88], EntityPig['Pig'/57, l='MpServer', x=55.88, y=66.00, z=1148.97], EntityPig['Pig'/63, l='MpServer', x=63.63, y=64.00, z=1276.34], EntityPig['Pig'/62, l='MpServer', x=60.25, y=69.00, z=1254.97], EntityPig['Pig'/61, l='MpServer', x=56.88, y=72.00, z=1245.34], EntityHorse['Horse'/60, l='MpServer', x=60.59, y=65.00, z=1193.28], EntityPig['Pig'/64, l='MpServer', x=55.66, y=64.00, z=1276.84], EntityPig['Pig'/65, l='MpServer', x=59.06, y=64.00, z=1276.00], EntityVillager['Villager'/76, l='MpServer', x=72.69, y=62.00, z=1176.69], EntityVillager['Villager'/77, l='MpServer', x=73.44, y=63.00, z=1174.38], EntityPlayerSP['FrenchFryCam'/173, l='MpServer', x=90.01, y=69.00, z=1199.05], EntityVillager['Villager'/78, l='MpServer', x=72.28, y=62.00, z=1175.78], EntityVillager['Villager'/79, l='MpServer', x=73.34, y=62.00, z=1175.53], EntityBat['Bat'/73, l='MpServer', x=66.22, y=30.00, z=1143.44], EntityVillager['Villager'/74, l='MpServer', x=78.75, y=61.00, z=1164.28], EntityVillager['Villager'/75, l='MpServer', x=76.78, y=63.00, z=1164.53], EntityPig['Pig'/84, l='MpServer', x=64.25, y=64.00, z=1271.06], EntityPig['Pig'/81, l='MpServer', x=76.44, y=69.00, z=1170.78], EntityVillager['Villager'/80, l='MpServer', x=67.28, y=66.00, z=1178.19], EntityHorse['Horse'/83, l='MpServer', x=79.25, y=65.00, z=1218.31], EntityBat['Bat'/82, l='MpServer', x=68.34, y=18.91, z=1212.75], EntityVillager['Villager'/93, l='MpServer', x=82.91, y=63.00, z=1175.53], EntityBat['Bat'/92, l='MpServer', x=93.41, y=37.00, z=1184.47], EntityBat['Bat'/95, l='MpServer', x=89.44, y=20.06, z=1208.19], EntityHorse['Horse'/94, l='MpServer', x=90.81, y=69.00, z=1201.41], EntityPig['Pig'/89, l='MpServer', x=82.56, y=69.00, z=1151.31], EntityPig['Pig'/88, l='MpServer', x=90.50, y=65.00, z=1151.78], EntityVillager['Villager'/91, l='MpServer', x=80.34, y=68.00, z=1164.28], EntityVillager['Villager'/90, l='MpServer', x=86.34, y=59.00, z=1165.78], EntityBat['Bat'/102, l='MpServer', x=106.75, y=24.09, z=1194.75], EntityPig['Pig'/103, l='MpServer', x=105.00, y=68.00, z=1204.97], EntityHorse['Donkey'/100, l='MpServer', x=109.97, y=64.00, z=1172.91], EntityPig['Pig'/101, l='MpServer', x=109.53, y=66.00, z=1178.53], EntityBat['Bat'/98, l='MpServer', x=103.47, y=12.03, z=1184.81], EntityPig['Pig'/96, l='MpServer', x=92.44, y=65.00, z=1234.81], EntityPig['Pig'/97, l='MpServer', x=107.88, y=63.00, z=1152.56], EntityPig['Pig'/110, l='MpServer', x=114.94, y=65.00, z=1224.03], EntityPig['Pig'/111, l='MpServer', x=123.19, y=66.00, z=1229.16], EntityPig['Pig'/108, l='MpServer', x=119.75, y=63.00, z=1183.31], EntityBat['Bat'/109, l='MpServer', x=117.13, y=27.09, z=1231.59], EntityBat['Bat'/228, l='MpServer', x=84.50, y=17.00, z=1205.50], EntityPig['Pig'/106, l='MpServer', x=100.22, y=69.00, z=1276.47], EntitySquid['Squid'/107, l='MpServer', x=128.13, y=61.44, z=1173.06], EntityPig['Pig'/104, l='MpServer', x=110.13, y=65.00, z=1224.91], EntityPig['Pig'/105, l='MpServer', x=103.63, y=65.00, z=1225.66], EntitySquid['Squid'/119, l='MpServer', x=133.28, y=62.47, z=1165.22], EntitySquid['Squid'/118, l='MpServer', x=137.63, y=59.31, z=1168.75], EntitySquid['Squid'/117, l='MpServer', x=137.56, y=50.47, z=1155.19], EntityPig['Pig'/113, l='MpServer', x=121.28, y=64.00, z=1256.13], EntityPig['Pig'/112, l='MpServer', x=125.16, y=67.00, z=1219.50], EntityPig['Pig'/126, l='MpServer', x=138.53, y=64.00, z=1279.44], EntityPig['Pig'/125, l='MpServer', x=137.25, y=64.00, z=1278.56], EntityPig['Pig'/124, l='MpServer', x=138.72, y=66.00, z=1238.13], EntitySquid['Squid'/123, l='MpServer', x=141.38, y=58.56, z=1168.94], EntityBat['Bat'/122, l='MpServer', x=125.03, y=12.03, z=1171.25], EntitySquid['Squid'/121, l='MpServer', x=135.84, y=53.97, z=1155.56], EntitySquid['Squid'/120, l='MpServer', x=137.84, y=57.13, z=1151.66]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Mac OS X (x86_64) version 10.6.8
Java Version: 1.6.0_65, Apple Inc.
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
Memory: 227643496 bytes (217 MB) / 470441984 bytes (448 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 3, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 5 mods loaded, 5 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
UCHIJAAAA Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
UCHIJAAAA corerm{1.2} [RikMuld's Core] (RikMuldsCore_1.2) 
UCHIJAAAA camping{2.2} [The Camping Mod 2] (TheCampingMod_2.2) 
Loaded coremods (and transformers): 
GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-1.6.36' Renderer: 'NVIDIA GeForce 320M OpenGL Engine'
Launched Version: 1.8-Forge11.14.3.1450
LWJGL: 2.9.2
OpenGL: NVIDIA GeForce 320M OpenGL Engine GL version 2.1 NVIDIA-1.6.36, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)

**Comment by Rikmuld** [comment]
fixed
