### ISSUE TITLE
I get this every time i try to connect to my own server StixxCraft.

### ISSUE THREAD

**Issue by Stixxhihat** [Rikmuld/CampingMod-mcmod#50]
My server is running KCauldron. Its start up fine with camping mod. My client, does not. I don't have any other mods installed other then the mods installed on the server. Please help.

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 7/9/15 6:41 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.rikmuld.corerm.core.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:190)
	at com.rikmuld.corerm.core.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:190)
	at scala.collection.Iterator$class.find(Iterator.scala:796)
	at scala.collection.AbstractIterator.find(Iterator.scala:1174)
	at scala.collection.IterableLike$class.find(IterableLike.scala:79)
	at scala.collection.AbstractIterable.find(Iterable.scala:54)
	at com.rikmuld.corerm.core.CoreUtils$InventoryUtils.containsItem(Utils.scala:190)
	at com.rikmuld.camping.core.Utils$CampingUtils.hasMap(Utils.scala:74)
	at com.rikmuld.camping.core.EventsClient.onOverlayRender(Events.scala:264)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_167_EventsClient_onOverlayRender_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:186)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.rikmuld.corerm.core.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:190)
	at com.rikmuld.corerm.core.CoreUtils$InventoryUtils$$anonfun$containsItem$2.apply(Utils.scala:190)
	at scala.collection.Iterator$class.find(Iterator.scala:796)
	at scala.collection.AbstractIterator.find(Iterator.scala:1174)
	at scala.collection.IterableLike$class.find(IterableLike.scala:79)
	at scala.collection.AbstractIterable.find(Iterable.scala:54)
	at com.rikmuld.corerm.core.CoreUtils$InventoryUtils.containsItem(Utils.scala:190)
	at com.rikmuld.camping.core.Utils$CampingUtils.hasMap(Utils.scala:74)
	at com.rikmuld.camping.core.EventsClient.onOverlayRender(Events.scala:264)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_167_EventsClient_onOverlayRender_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:186)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['DLCGaming'/1284, l='MpServer', x=231.39, y=106.62, z=-138.12]]
	Chunk stats: MultiplayerChunkCache: 190, 190
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (39,105,408), Chunk: (at 7,6,8 in 2,25; contains blocks 32,0,400 to 47,255,415), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 165460377 game time, 120868315 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityMinecartEmpty['entity.MinecartRideable.name'/1285, l='MpServer', x=239.47, y=104.34, z=-169.53], EntityMinecartEmpty['entity.MinecartRideable.name'/1286, l='MpServer', x=242.22, y=104.34, z=-169.53], EntityFerfari['entity.carsanddrives.Ferfari.name'/1287, l='MpServer', x=241.88, y=105.00, z=-170.47], EntityItemFrame['entity.ItemFrame.name'/1288, l='MpServer', x=198.50, y=106.50, z=-161.06], EntityItemFrame['entity.ItemFrame.name'/1289, l='MpServer', x=197.50, y=106.50, z=-161.06], GCEntityClientPlayerMP['DLCGaming'/1284, l='MpServer', x=231.39, y=106.62, z=-138.12]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1150039800 bytes (1096 MB) / 1932787712 bytes (1843 MB) up to 1932787712 bytes (1843 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.112.1374 Minecraft Forge 10.13.3.1374 23 mods loaded, 23 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.112.1374} [Forge Mod Loader] (forge-1.7.10-10.13.3.1374-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.3.1374} [Minecraft Forge] (forge-1.7.10-10.13.3.1374-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	securitycraft{v1.7.4.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.7.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.7.3} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	carsanddrives{1.0.9} [Cars and Drives] (Cars and Drives Mod 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	props{2.0.1} [Decocraft] (Decocraft-2.0.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: 1.7.10-Forge10.13.3.1374-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 9400 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Rikmuld** [comment]
I'm sorry but the version of the mod you are using is no longer supported (I will only work no the version for MC 1.8).
